### ISSUE TITLE
Runtime Exception on Export to PDF

### ISSUE THREAD

**Issue by 1papaya** [zeeshanu/opus#104]
Seems the Export to PDF function executes a hardcoded path to `C:/wkhtmltopdf/bin/wkhtmltopdf.exe`, which does not exist on my machine

![screenshot-area-2017-10-17-163944](https://user-images.githubusercontent.com/25945912/31693074-f8d90e10-b359-11e7-919c-0aa8cfa515ac.png)

**Comment by facundofarias** [comment]
Hello @1papaya,

It seems to be that it works in Windows, but not Linux/OSX.
The change I did to make it work was: 

Add the dependency `"h4cc/wkhtmltopdf-amd64": "0.12.3"` in the composer.json file, and then in the file `wiki/config/snappy.php`, use the following setting:
```
    'pdf' => array(
        'enabled' => true,
        'binary' => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),
        'timeout' => false,
        'options' => [],
        'env'     => [],
    ),
```
Hope it helps!
