### ISSUE TITLE
 php artisan db:seed fails

### ISSUE THREAD

**Issue by michaelhonasan9** [zeeshanu/opus#112]
Hi,

I'm having trouble executing  "php artisan db:seed". I followed all the instruction and works well, however, when I executed db:seed, I got this error "Seeding: Database\Seeds\Components\Role\RolesTableSeeder

  [ErrorException]
  count(): Parameter must be an array or an object that implements Countable
"
You can refer also from attached image below.
I have PHP version 7.2.4 and Mysql version 5.1.73.

Thank you and I hope i can hear a response coming from you soon.
![error](https://user-images.githubusercontent.com/28986358/38164094-83de0bda-34ee-11e8-9c5d-8b7e0d4fd0b1.PNG)

**Comment by deepu9** [comment]
Hi @michaelhonasan9,
Maybe try debugging in RoleTableSeeder to see if something is receiving a string instead of an array.

**Comment by lagbox** [comment]
@michaelhonasan9 

This is an issue that `"laravel/framework": "5.3.*",` wont bring in the latest state of the 5.3 branch that has changes to work around the `count` issues that have come up because of PHP 7.2 (specifically a PR to fix the `count` call in `callScope`)
