### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by Sekonda** [zeeshanu/opus#18]
Hey,

Just downloaded this to have a look around and it seems there are number of missing images.

- basic_eye.svg
- basic_elaboration_todolist_check.svg
- software_paragraph_space_after.svg
- software_pencil.svg
- basic_gear.svg
- basic_message_multiple.svg
- basic_elaboration_message_sad.svg
- basic_book.svg

I'll update this if I find any more

**Comment by zeeshanu** [comment]
@Sekonda Thanks for posting the issue. I just removed all the svg beacuse they might slow the page loading. In dev branch I created a PR for this that replaces all svg with font awesome. I will merge it later to master branch. ☺
