### ISSUE TITLE
FatalErrorException in RouteServiceProvider.php line 7

### ISSUE THREAD

**Issue by simondahla** [zeeshanu/opus#22]
Getting this error message when trying to run the application:

```
FatalErrorException in RouteServiceProvider.php line 7:
syntax error, unexpected '{', expecting identifier (T_STRING)
```

The line it's referring to is: [`use App\Models\{User, Space, Wiki, Team, Page, Role};`](https://github.com/zeeshanu/opus/blob/master/app/Providers/RouteServiceProvider.php#L7)

**Comment by zeeshanu** [comment]
@simondahla what is the php version do you have?

**Comment by simondahla** [comment]
@zeeshanu 

```
vagrant@scotchbox:/var/www/opus.local$ php -v
PHP 7.0.17-2+deb.sury.org~trusty+1 (cli) (built: Mar 15 2017 09:38:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17-2+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

```

I tried to rewrite that line to 
```
use App\Models\User;
use App\Models\Space;
use App\Models\Wiki;
use App\Models\Team;
use App\Models\Page;
use App\Models\Role;

```
It seems to fix the problem, but the that kind of error is then found in [Wiki.php](https://github.com/zeeshanu/opus/blob/master/app/Models/Wiki.php) and probably all other files with that syntax...

**Comment by simondahla** [comment]
@zeeshanu 

```
vagrant@scotchbox:/var/www/opus.local$ php -v
PHP 7.0.17-2+deb.sury.org~trusty+1 (cli) (built: Mar 15 2017 09:38:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17-2+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

```

I tried to rewrite that line to 
```
use App\Models\User;
use App\Models\Space;
use App\Models\Wiki;
use App\Models\Team;
use App\Models\Page;
use App\Models\Role;

```
It seems to fix the problem, but the that kind of error is then found in [Wiki.php](https://github.com/zeeshanu/opus/blob/master/app/Models/Wiki.php) and probably all other files with that syntax...

**Comment by simondahla** [comment]
Also tried to upgrade to PHP 7.1 but without success.

```
vagrant@scotchbox:/var/www/opus.local$ php -v
PHP 7.1.3-2+deb.sury.org~trusty+1 (cli) (built: Mar 15 2017 09:53:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-2+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

```

**Comment by zeeshanu** [comment]
@simondahla This is strange because I have PHP 7.0.9 and everything is working fine. As you can see in PHP documentation we can group use statements in php like this:
```
// PHP 7+ code
use some\namespace\{ClassA, ClassB, ClassC as C};
use function some\namespace\{fn_a, fn_b, fn_c};
use const some\namespace\{ConstA, ConstB, ConstC};
```

**Comment by sandeepscet** [comment]
Solved after PHP 7 installation.

**Comment by simondahla** [comment]
@zeeshanu I hear you. As you can see I'm using PHP 7.1.3 and it's still not working.

Any other suggestions on how to solve this?

**Comment by zeeshanu** [comment]
@simondahla  To solve your issue just explode the grouped use statements like this
```
use {ClassA, ClassB};
```
with
```
use ClassA;
use ClassB;
```
