### ISSUE TITLE
404 on JS and css urls

### ISSUE THREAD

**Issue by sandeepscet** [zeeshanu/opus#32]
Getting 404 for every js and css
Url : http://localhost/css/bootstrap.min.css
Reason :  
 JS and CSS included with / in master.blade.php , that will download from base domain url.
`<link rel="stylesheet" href="/css/bootstrap.min.css">
`
After all this stuff, still js and css not loading on login and all pages except landing page.

Url : http://localhost/opus/public/team/css/bootstrap.min.css
I didnt find any team folder inside public.

Configs:
```
.env : APP_URL=http://localhost/opus
app.php :  'url' => env('APP_URL', 'http://localhost/opus'),
```

Using xampp .
Not added any project specific htacccess enty.
i did setup laravel first time.

Am i missed anything or is this issue?

**Comment by zeeshanu** [comment]
@sandeepscet To run this application open your terminal and go to the root folder of this application and run the following command inside your terminal:
```
php artisan serve
```
After that open `localhost:8000` in your browser.

**Comment by sandeepscet** [comment]
@zeeshanu 
Its working. You can close this issue.
Also , Please update  the readme file to avoid this kind of issue.
