### ISSUE TITLE
How to serve?

### ISSUE THREAD

**Issue by absolutejam** [zeeshanu/opus#36]
I commented on the 'How do I start?' issue (https://github.com/zeeshanu/opus/issues/1#issuecomment-287646648) but it's closed so I'm not sure anyone will see it!

Just curious, I've built the app as per instructions, but I'm not sure how to serve it? I tried `php artisan serve --port=80`, serving it behind nginx... To no avail. Can you let me know what I'm missing please?

Thanks!

**Comment by zeeshanu** [comment]
@absolutejam This issue is already resolved. Please refer to  issue [#32] (https://github.com/zeeshanu/opus/issues/32)

**Comment by absolutejam** [comment]
As per https://github.com/zeeshanu/opus/issues/32#issuecomment-287627161, this isnt very clear in the documentation, and isn't serving this way only supposed to be for development?

As I mentioned above, I've tried that already and it isn't working (From within a Docker container with ports `8000` mapped through). stdout shows `Laravel development server started on http://127.0.0.1:8000/` but I just get the following when I try to browse to it:

![2017-03-21t13 54 57 00 00](https://cloud.githubusercontent.com/assets/6817942/24150598/0bdda6e0-0e3e-11e7-9a49-ed515b8f8cd1.png)

**Comment by absolutejam** [comment]
I've been busy over the last few days but I realised I was being dumb and re-attempted this. Issue was because I didn't specify `--host=0.0.0.0` when running with Docker. Will try and tidy it up a little and see if you want it as a starting point?
