### ISSUE TITLE
New users unauthorised to create wikis

### ISSUE THREAD

**Issue by jahvi** [zeeshanu/opus#62]
Similar to #8 I'm getting `Unauthorized` when trying to create wikis with newly invited users, it works fine for the account that originally created the team.

**Steps to replicate**
1. Invite new user
2. Accept invite link email and register
3. Login and try to create a wiki

It looks like the main issue is that the following line in the `hasPermissions()` function returns empty:

`$roles = $this->with('roles')->findOrFail(Auth::user()->id)->roles;`

Maybe the roles are not getting assigned correctly on new users?

**Comment by zeeshanu** [comment]
You need to run `db:seed` command.

**Comment by jahvi** [comment]
I did run it

**Comment by jahvi** [comment]
Thanks, I'm still seeing the same issue though but now the primary account can't create wikis either, I get a 403 page for all admin users now.

**Comment by jahvi** [comment]
I couldn't run `db:seed` this time though, I'm getting the following error not sure if it's related:

`Class Database\Seeds\Components\Role\RolesTableSeeder does not exist`

**Comment by zeeshanu** [comment]
@jahvi Can you please run the following commands and let me know if you still have the same problem:
```
php artisan migrate:refresh
php artisan db:seed
```

**Comment by jahvi** [comment]
Yes my bad I needed to `composer dump-autoload` as well after the update. Can confirm it works now 👍
