### ISSUE TITLE
Provide Dockerfile for easier deployment

### ISSUE THREAD

**Issue by dAnjou** [zeeshanu/opus#65]

**Comment by shadowhand** [comment]
I've started [opus-docker](https://github.com/shadowhand/opus-docker) but am running into some issues when trying to run `php artisan migrate` inside the `php` container:

```
# php artisan migrate
                                                                                                                        
  [Illuminate\Database\QueryException]                                                                                        
  could not find driver (SQL: select * from information_schema.tables where table_schema = opus and table_name = migrations)
```

Anyone know why this would be happening?

**Comment by dAnjou** [comment]
It probably means that you don't have the database drivers installed. Try installing some: https://pkgs.alpinelinux.org/packages?name=php*sql*&branch=v3.4&arch=x86_64

**Comment by shadowhand** [comment]
@dAnjou perfect, that got me up to being able to run the migration and seed, by patching zeeshanu/opus#69

Then I ran into additional problems with the paths that Laravel uses for caching. I tried to switch to Redis but Predis falls apart because of nrk/predis#422.

My repo has been updated with my changes thus far.

**Comment by dAnjou** [comment]
@shadowhand, I just looked through your repo and it's good effort so far but I have some remarks. But I'll open an issue in your project. We can come back here once they are resolved.

**Comment by SalahAdDin** [comment]
@dAnjou What's about this https://github.com/SalahAdDin/opus?
