### ISSUE TITLE
Offer SSO options

### ISSUE THREAD

**Issue by dAnjou** [zeeshanu/opus#66]
> **Motivation**
> 
> As companies grow, it becomes difficult to manage and communicate the knowledge across different departments [...]

That's very very true. But you know what's also true? They have a hard time managing people and their accounts. What that means is that you should definitely offer SSO options. Companies I have worked for are using Google to manage user accounts (check out [their developer docs](https://developers.google.com/identity/sign-in/web/)). But it can also be LinkedIn (check out [their developer docs](https://developer.linkedin.com/docs/signin-with-linkedin)) or many other widely adopted platforms.

**Comment by shadowhand** [comment]
We use Google for user accounts at my company. Being able to SSO with [oauth2-google](https://github.com/thephpleague/oauth2-google) would be ideal.

**Comment by zeeshanu** [comment]
@dAnjou It's a good idea to let people register with their google credentials. And I will surely add this functionality later. :+1:

**Comment by shadowhand** [comment]
So... leave it open until you do?

**Comment by b00rek** [comment]
Also logon with an Active Directory account would be great for companies... This is what I'm personally looking for - a simple, clean wiki, that can either be integrated with NextCloud, or be able authenticate against AD.
