### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by Allineer** [zeeshanu/opus#73]
Can't login to demo account with this credentials:

```
Team Name:  Opus
Email:  admin@admin.com
Password:  admin
```

`Email or password is not valid.`

**Comment by Allineer** [comment]
```Team Name:  Opus
    Email:  admin@admin.com
 Password:  admin```

**Comment by Sekonda** [comment]
@zeeshanu

**Comment by zeeshanu** [comment]
@Allineer @Sekonda I am too busy these days but when it will be fixed i will let you know here.
