### ISSUE TITLE
Demo domain

### ISSUE THREAD

**Issue by m1guelpf** [zeeshanu/opus#76]
Hi!
I've seen that you offer a demo, but it hasn't got any domain.
I would like to offer opus.miguelpiedrafita.com if you want

**Comment by zeeshanu** [comment]
@m1guelpf Actually, I do not have the hosting either (college student here ;)), it will be down in a few days, so I am actually looking for the sponsor for that as well. Will update the readme. But thanks for the offer :smile:

**Comment by m1guelpf** [comment]
@zeeshanu I have unlimited GB in my hosting account, but I can't give you access for security reasons. Maybe I could upload the demo and provide a database, and you ping me whan there is an update?

**Comment by SalahAdDin** [comment]
Opus, admin@admin.com, and admin doesn't works in demo.

**Comment by NigelGreenway** [comment]
What about using heroku? You have a free tier available and it's fairly easy to set up.
