### ISSUE TITLE
Layout issue after installation?!

### ISSUE THREAD

**Issue by frenci** [zeeshanu/opus#79]
Hi guys,
I am trying to run opus locally on my machine (Windows OS) and I get the following screen. Tried it on a macOS environment, same result.

<img width="699" alt="screen shot 2017-04-22 at 11 31 30 pm" src="https://cloud.githubusercontent.com/assets/13355808/25308437/6ccdb906-27b4-11e7-9fa8-8f7e7c9aa939.png">
I am using MAMP: PHP version 7.0.13,  MySQL 5.6.34

Am I doing something wrong? Do you have a fix for this issue?

Thanks!

**Comment by zeeshanu** [comment]
Can you please upload the image of your Browser Console.

**Comment by frenci** [comment]
@zeeshanu Here you go:
<img width="1235" alt="screen shot 2017-04-27 at 6 19 16 pm" src="https://cloud.githubusercontent.com/assets/13355808/25493508/b58ebfc6-2b76-11e7-9a0f-81c0662c799f.png">

**Comment by zeeshanu** [comment]
@frenci Can you please also share your network output? :sweat_smile:

**Comment by frenci** [comment]
@zeeshanu Sorry, I am still a rookie :-)
<img width="1230" alt="screen shot 2017-04-27 at 10 21 17 pm" src="https://cloud.githubusercontent.com/assets/13355808/25502752/48fed194-2b98-11e7-8e87-ba3a8b85d0e2.png">
<img width="1238" alt="screen shot 2017-04-27 at 10 22 25 pm" src="https://cloud.githubusercontent.com/assets/13355808/25502755/4b40112a-2b98-11e7-9159-aa1d801961f2.png">

**Comment by frenci** [comment]
Fixed it by running Artisan command `php artisan serve`. Can you please help me to understand the WHY  :-)

**Comment by zeeshanu** [comment]
@frenci `php artisan serve` runs a serve for you and gives you a URL to access the application on that; without having to setup apache or nginx etc.

**Comment by SalahAdDin** [comment]
@zeeshanu But this error shouldn't happen with a normal `nGinx` or  `apache` installation!
