### ISSUE TITLE
php artisan migrate not working

### ISSUE THREAD

**Issue by ilkiny** [zeeshanu/opus#90]
```
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/home.dev/lab.home.dev/artisan on line 31

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/home.dev/lab.home.dev/artisan on line 31

```

**Comment by ilkiny** [comment]
@zeeshanu

**Comment by zeeshanu** [comment]
@ilkiny What is the version of PHP do you have?

**Comment by ilkiny** [comment]
Version 7

**Comment by zeeshanu** [comment]
@ilkiny Did you run `composer install` command after cloning this repository?

**Comment by ilkiny** [comment]
Yes, but the database is not being created. @zeeshanu

**Comment by ilkiny** [comment]
The problem continues. @zeeshanu

**Comment by SalahAdDin** [comment]
@ilkiny was it solved?

**Comment by indiesk** [comment]
@ilkiny If resolved, can you share? I'm having the same issue.

**Comment by ilkiny** [comment]
Hello, @indiesk I requested the database file from someone else and installed it manually.

[https://gist.github.com/ilkiny/5091c884d8e75d807c890c12f81325da](url)

@SalahAdDin Yep

**Comment by indiesk** [comment]
@ilkiny Thanks for sharing

For anyone facing a similar issue, I've found out that for the mac terminal, there are cases where `php-cli` command needs to be used instead of `php`. This resolved my case.
